# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    steps:

    - name: you must have the full xcode installed
      run: ls /Applications/Xcode_11.5_beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk
    # Runs a single command using the runners shell
    - name: Download reason-mobile
      run: git clone https://github.com/EduardoRFS/reason-mobile.git --depth 1

    # Runs a set of commands using the runners shell
    - name: Download revery
      working-directory: reason-mobile
      run: git clone https://github.com/revery-ui/revery.git --branch master

    # patch to fix problems with iOS and Android, also adds Xcode folder
    - name: Apply patch for ios+android
      working-directory: reason-mobile/revery
      run: patch -p1 < ../patches/revery/files/android+ios.patch
